name: 'tag-version'
description: 'Provides automated versioning of your commits using git tags each time your CI/CD workflow runs.'
branding:
  icon: 'tag'
  color: 'green'
outputs:
  revision:
    description: 'The new version that was created and tagged in the format of <major>.<minor>.<build>[.<pre-release-tag>]'
    value: ${{ steps.tag-version.outputs.revision }}
  is-prerelease:
    description: 'Is true if this is a release into a non-production environment and indicates the build may be unstable. Returns false otherwise.'
    value: ${{ steps.tag-version.outputs.is-prerelease }}
runs:
  using: composite
  steps:
    uses: actions/setup-python@v2
    with:
      python-version: 3.8
  
    - id: tag-version
      run: |
        pip install semver
        python $GITHUB_ACTION_PATH/src/tag-version.py > version
